<?php
// src/Controller/ArticlesController.php

namespace App\Controller;

use Cake\ORM\TableRegistry;

class AdminsController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Units');
        $this->loadModel('');
    }

    public function index()
    {
    }
    public function  create(){
        $unitTable = TableRegistry::getTableLocator()->get('units');

        if($this->request->is('post')) {
            $unitCode = $this->request->getData('unitCode');
            $title = $this->request->getData('title');
            $semester = $this->request->getData('semester');
            $year = $this->request->getData('year');
            $unitMatches = $unitTable->find()->where(['code'=>$unitCode, 'semester'=>$semester,'year'=>$year]);
            $matches = [];
            foreach($unitMatches as $unitMatch){
                array_push($matches,$unitMatch);
            }
            debug(count($matches));
            if (count($matches) === 1){
                $this->Flash->error('Unit Already Existed');
            }else{
                $newUnit = $unitTable->newEntity();
                $newUnit->title = $title;
                $newUnit->code = $unitCode;
                $newUnit->semester = $semester;
                $newUnit->year = $year;

                if ($this->Units->save($newUnit)) {
                    $this->Flash->success(__('The new unit'.$newUnit->code.' has been saved.'));

                    return $this->redirect(['controller'=>'admins','action' => 'index']);
                }else{
                    $this->Flash->error(__('The new unit' .$newUnit->code.'could not be saved. Please, try again.'));
                }

            }
//            debug($matches);
//            echo $unitCode . $semester . $year;
//            debug(count($this->request->getData()));
        }

    }

    public function createPeerReview(){

    }
    public function submit(){
        if($this->request->is('post')){
            var_dump($this->request->getData());
        }
    }
}
